### ISSUE TITLE
Silly Question

### ISSUE THREAD

**Issue by dovy** [tehraven/PHRetsForCREA#1]
What is CREA?

**Comment by jgrahamcrea** [comment]
Canadian Real Estate Association.

On Jul 11, 2015, at 11:23 AM, Dovy Paukstys <notifications@github.com<mailto:notifications@github.com>> wrote:

What is CREA?

—
Reply to this email directly or view it on GitHubhttps://github.com/tehraven/PHRetsForCREA/issues/1.

Jason Graham
Manager, Application Development / Gestionnaire de développement d’applications
jgraham@crea.ca

The Canadian Real Estate Association / L'Association canadienne de l'immeuble
200 Catherine Street, 6th Floor / 200, rue Catherine, 6e étage    Ottawa, ON K2P 2K9
Tel/Tél: +1 (613) 237-7111    Fax/Téléc: +1 (613) 234-2567

www.crea.cahttp://www.crea.ca     www.REALTOR.cahttp://www.REALTOR.ca     www.ICX.cahttp://www.ICX.ca     www.REALTORSCare.cahttp://www.realtorscare.ca
This e-mail and any attachments may contain information that is privileged and/or confidential. If you are not the intended recipient and appear to have received this e-mail in error, please notify us immediately and then delete all copies from your computer system. Any unauthorized use, copying or further distribution is prohibited.
Il est possible que certains renseignements contenus dans le présent courriel ainsi que toute pièce jointe soient confidentiels. Si vous n’êtes pas le destinataire prévu et que vous croyez avoir reçu le présent courriel par erreur, nous vous prions de nous le signaler immédiatement et de supprimer toute copie de ce courriel de votre système informatique. Toute utilisation, reproduction ou diffusion non autorisée du présent courriel est interdite.

**Comment by dovy** [comment]
Awesome. Why not merge this into PHRETS? Seems like it should go together.

**Comment by tehraven** [comment]
PHRets needed to be modified a bit to make the version of CREA we were using work. There were some difference. Merging these differences in wouldn't work for any other RETS server.

Which reminds me, I have to update this with the newest changes.

Cheers.
